---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  # No need to detail more: https://github.com/opscode/kitchen-vagrant#-default-configuration
- name: ubuntu-12.04

  # for an unknow reason the debian 7 provided by opscode do not work for me, so I found an other one
- name: debian-7.1.0
  driver_config:
    provider: virtualbox
    box: ffuenf-debian-7.1.0
    box_url: https://s3-eu-west-1.amazonaws.com/ffuenf-vagrant-boxes/chef-11.6.0/debian-7.1.0-amd64.box
  run_list: ["recipe[remove_exim4]"]

#- name: ubuntu-10.04
#  driver_config:
#    box: opscode-ubuntu-10.04
#    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_chef-11.2.0.box
#- name: centos-6.3
#  driver_config:
#    box: opscode-centos-6.3
#    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.3_chef-11.2.0.box
#- name: centos-5.8
#  driver_config:
#    box: opscode-centos-5.8
#    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-5.8_chef-11.2.0.box

suites:
- name: default
  run_list: ["recipe[git]", "recipe[opensmtpd]"]
  attributes: {}
